-- CreateTable
CREATE TABLE "RawCcodRecord" (
    "id" SERIAL NOT NULL,
    "titleNumber" TEXT,
    "tenure" TEXT,
    "propertyAddress" TEXT,
    "district" TEXT,
    "county" TEXT,
    "region" TEXT,
    "postcode" TEXT,
    "multipleAddressIndicator" TEXT,
    "pricePaid" INTEGER,
    "proprietorName1" TEXT,
    "companyRegistrationNo1" TEXT,
    "proprietorshipCategory1" TEXT,
    "proprietorAddress1_1" TEXT,
    "proprietorAddress1_2" TEXT,
    "proprietorAddress1_3" TEXT,
    "proprietorName2" TEXT,
    "companyRegistrationNo2" TEXT,
    "proprietorshipCategory2" TEXT,
    "proprietorAddress2_1" TEXT,
    "proprietorAddress2_2" TEXT,
    "proprietorAddress2_3" TEXT,
    "proprietorName3" TEXT,
    "companyRegistrationNo3" TEXT,
    "proprietorshipCategory3" TEXT,
    "proprietorAddress3_1" TEXT,
    "proprietorAddress3_2" TEXT,
    "proprietorAddress3_3" TEXT,
    "proprietorName4" TEXT,
    "companyRegistrationNo4" TEXT,
    "proprietorshipCategory4" TEXT,
    "proprietorAddress4_1" TEXT,
    "proprietorAddress4_2" TEXT,
    "proprietorAddress4_3" TEXT,
    "dateProprietorAdded" TIMESTAMP(3),
    "additionalProprietorIndicator" TEXT,
    "ingestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RawCcodRecord_pkey" PRIMARY KEY ("id")
);
